# Generated by Django 3.2.8 on 2021-11-12 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('активно', 'АКТИВНО'), ('отложено', 'ОТЛОЖЕНО'), ('выполнено', 'ВЫПОЛНЕНО')], default='активно', max_length=10),
        ),
    ]
